file_format: "1"
id: wakeyb
name: Wakeyb
type: shield
url: https://github.com/vicenterocha/wake-yboard
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
siblings:
  - corne_left
  - corne_right